FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN apt-get update && apt-get -y --no-install-recommends install \
    dnsutils \
    netcat-openbsd \
    net-tools \
    iputils-ping \
    nano \
    wget \
    curl \
    ca-certificates \
    openssh-server \
    && rm -rf /var/lib/apt/lists/*

COPY --chmod=755 docker-entrypoint-ssh.sh /usr/bin/

ENTRYPOINT ["docker-entrypoint-ssh.sh"]